service: dreamabout-image-resizer

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
          Resource: "arn:aws:s3:::static.getdreamshop.dk/*"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource: "arn:aws:s3:::static.getdreamshop.dk/*"
functions:
  resize:
    memorySize: 1536 # in megabytes
    timeout: 60 # optional, in seconds, default is 6
    handler: src/handlers/resizer/index.handler
    events:
      - httpApi: '*'
    environment:
      # Provide your bucket name here
      BUCKET: static.getdreamshop.dk
      REGION: eu-west-1
      STAGE: ${sls:stage}
      URL: https://s3.eu-west-1.amazonaws.com/static.getdreamshop.dk/
      DEBUG: true
  on-product-upload:  ${file(./serverless/${sls:stage}/onProductUpload.yml)}
package:
  patterns:
    - "src/"
    - 'node_modules/'
